/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#38485d',
        'inverse-primary': '#b8c4ff',
        'on-secondary-fixed': '#0b1c30',
        background: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-container-highest': '#e0e3e5',
        primary: '#00288e',
        surface: '#f7f9fb',
        outline: '#757684',
        'on-tertiary-fixed': '#001e2f',
        'tertiary-fixed': '#c9e6ff',
        'surface-variant': '#e0e3e5',
        'on-secondary-container': '#54647a',
        'on-surface-variant': '#444653',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001453',
        'error-container': '#ffdad6',
        'secondary-container': '#d0e1fb',
        'on-background': '#191c1e',
        'on-tertiary-container': '#68c4ff',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#b8c4ff',
        'on-primary-container': '#a8b8ff',
        'on-surface': '#191c1e',
        'surface-container': '#eceef0',
        'surface-bright': '#f7f9fb',
        'surface-tint': '#3755c3',
        'surface-container-low': '#f2f4f6',
        'on-primary-fixed-variant': '#173bab',
        'inverse-surface': '#2d3133',
        'surface-container-high': '#e6e8ea',
        'tertiary-container': '#005074',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed': '#d3e4fe',
        secondary: '#505f76',
        'primary-container': '#1e40af',
        'primary-fixed': '#dde1ff',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'outline-variant': '#c4c5d5',
        'tertiary-fixed-dim': '#89ceff',
        'on-tertiary-fixed-variant': '#004c6e',
        'on-secondary': '#ffffff',
        tertiary: '#003853',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
